name: chatwork

on:
  issues:
    types:
      - opened
      - edited

  issue_comment:
    types:
      - created
      - edited

  pull_request:
    types:
      - opened
      - edited

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          roomId: ${{ secrets.CHATWORK_ROOM_ID }}
          token: ${{ secrets.CHATWORK_API_TOKEN }}
          mapping: |
            {
              "mechiru": "chatwork/mechiru"
            }
